SELECT STUDENTS.NAME
FROM STUDENTS
LEFT JOIN FRIENDS ON STUDENTS.ID = FRIENDS.ID
LEFT JOIN PACKAGES SELF ON STUDENTS.ID = SELF.ID
LEFT JOIN PACKAGES OTHER ON FRIENDS.FRIEND_ID = OTHER.ID
WHERE OTHER.SALARY >= SELF.SALARY
ORDER BY OTHER.SALARY;